#FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7
#COPY ./app /app
#RUN pip install -r /app/requirements.txt

FROM python:3.7
COPY ./app /app
WORKDIR /app
RUN pip install -r requirements.txt 
CMD ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "80"]